//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Apps.Model
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class AutofacDBEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“AutofacDBEntities”部分中的连接字符串初始化新 AutofacDBEntities 对象。
        /// </summary>
        public AutofacDBEntities() : base("name=AutofacDBEntities", "AutofacDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 AutofacDBEntities 对象。
        /// </summary>
        public AutofacDBEntities(string connectionString) : base(connectionString, "AutofacDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 AutofacDBEntities 对象。
        /// </summary>
        public AutofacDBEntities(EntityConnection connection) : base(connection, "AutofacDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Student> Student
        {
            get
            {
                if ((_Student == null))
                {
                    _Student = base.CreateObjectSet<Student>("Student");
                }
                return _Student;
            }
        }
        private ObjectSet<Student> _Student;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Teacher> Teacher
        {
            get
            {
                if ((_Teacher == null))
                {
                    _Teacher = base.CreateObjectSet<Teacher>("Teacher");
                }
                return _Teacher;
            }
        }
        private ObjectSet<Teacher> _Teacher;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 Student EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToStudent(Student student)
        {
            base.AddObject("Student", student);
        }
    
        /// <summary>
        /// 用于向 Teacher EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToTeacher(Teacher teacher)
        {
            base.AddObject("Teacher", teacher);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AutofacDBModel", Name="Student")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Student : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Student 对象。
        /// </summary>
        /// <param name="gKey">gKey 属性的初始值。</param>
        public static Student CreateStudent(global::System.Guid gKey)
        {
            Student student = new Student();
            student.gKey = gKey;
            return student;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid gKey
        {
            get
            {
                return _gKey;
            }
            set
            {
                if (_gKey != value)
                {
                    OngKeyChanging(value);
                    ReportPropertyChanging("gKey");
                    _gKey = StructuralObject.SetValidValue(value, "gKey");
                    ReportPropertyChanged("gKey");
                    OngKeyChanged();
                }
            }
        }
        private global::System.Guid _gKey;
        partial void OngKeyChanging(global::System.Guid value);
        partial void OngKeyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sName
        {
            get
            {
                return _sName;
            }
            set
            {
                OnsNameChanging(value);
                ReportPropertyChanging("sName");
                _sName = StructuralObject.SetValidValue(value, true, "sName");
                ReportPropertyChanged("sName");
                OnsNameChanged();
            }
        }
        private global::System.String _sName;
        partial void OnsNameChanging(global::System.String value);
        partial void OnsNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> iAge
        {
            get
            {
                return _iAge;
            }
            set
            {
                OniAgeChanging(value);
                ReportPropertyChanging("iAge");
                _iAge = StructuralObject.SetValidValue(value, "iAge");
                ReportPropertyChanged("iAge");
                OniAgeChanged();
            }
        }
        private Nullable<global::System.Int32> _iAge;
        partial void OniAgeChanging(Nullable<global::System.Int32> value);
        partial void OniAgeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> dAddTime
        {
            get
            {
                return _dAddTime;
            }
            set
            {
                OndAddTimeChanging(value);
                ReportPropertyChanging("dAddTime");
                _dAddTime = StructuralObject.SetValidValue(value, "dAddTime");
                ReportPropertyChanged("dAddTime");
                OndAddTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _dAddTime;
        partial void OndAddTimeChanging(Nullable<global::System.DateTime> value);
        partial void OndAddTimeChanged();

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AutofacDBModel", Name="Teacher")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Teacher : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Teacher 对象。
        /// </summary>
        /// <param name="gKey">gKey 属性的初始值。</param>
        public static Teacher CreateTeacher(global::System.Guid gKey)
        {
            Teacher teacher = new Teacher();
            teacher.gKey = gKey;
            return teacher;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid gKey
        {
            get
            {
                return _gKey;
            }
            set
            {
                if (_gKey != value)
                {
                    OngKeyChanging(value);
                    ReportPropertyChanging("gKey");
                    _gKey = StructuralObject.SetValidValue(value, "gKey");
                    ReportPropertyChanged("gKey");
                    OngKeyChanged();
                }
            }
        }
        private global::System.Guid _gKey;
        partial void OngKeyChanging(global::System.Guid value);
        partial void OngKeyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sName
        {
            get
            {
                return _sName;
            }
            set
            {
                OnsNameChanging(value);
                ReportPropertyChanging("sName");
                _sName = StructuralObject.SetValidValue(value, true, "sName");
                ReportPropertyChanged("sName");
                OnsNameChanged();
            }
        }
        private global::System.String _sName;
        partial void OnsNameChanging(global::System.String value);
        partial void OnsNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> iAge
        {
            get
            {
                return _iAge;
            }
            set
            {
                OniAgeChanging(value);
                ReportPropertyChanging("iAge");
                _iAge = StructuralObject.SetValidValue(value, "iAge");
                ReportPropertyChanged("iAge");
                OniAgeChanged();
            }
        }
        private Nullable<global::System.Int32> _iAge;
        partial void OniAgeChanging(Nullable<global::System.Int32> value);
        partial void OniAgeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> dAddTime
        {
            get
            {
                return _dAddTime;
            }
            set
            {
                OndAddTimeChanging(value);
                ReportPropertyChanging("dAddTime");
                _dAddTime = StructuralObject.SetValidValue(value, "dAddTime");
                ReportPropertyChanged("dAddTime");
                OndAddTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _dAddTime;
        partial void OndAddTimeChanging(Nullable<global::System.DateTime> value);
        partial void OndAddTimeChanged();

        #endregion

    }

    #endregion

}
